// Auto-generated from the real_bond_pool.xlsx data set: 184 real individual bonds sourced
// from the live, published holdings of three major bond ETFs (AGG, LQD, EMB — fetched from
// ishares.com on 17 Aug 2026), plus a handful of well-known funds referenced in Titan Square
// Mile Academy research. Every issuer, coupon, maturity, CUSIP/ISIN, and (where published)
// price/YTM is real, as-published data as of that fetch date — not synthetic. Treat prices,
// YTMs and durations as an illustrative snapshot, not tradeable quotes; this is not investment
// advice. The 17 fund/ETF-level rows in the source file carry no coupon/maturity/YTM data at
// all (fund-level, not a single security) and are deliberately excluded here.
//
// "duration" is NOT in the source file — it's calculated here from each bond's real coupon,
// maturity and YTM using standard bond math (modified duration via discounted cash flows,
// semiannual compounding, valued as of 17 Aug 2026 to match the data's fetch date). It is a
// derived figure, not a published one.
//
// The source file has no credit-rating column and ratings can't be reliably derived from the
// other fields, so this app has no rating filter — every instrument here is a real, named,
// unrated-in-this-dataset security.
export const BONDS = [
  {
    "id": "BND-0018",
    "name": "US Treasury Note 4.63% 2035-02-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.63,
    "maturity": "2035-02-15",
    "price": null,
    "ytm": 4.57,
    "duration": 6.97,
    "sector": "Treasury",
    "cusip": "91282CMM0",
    "isin": "US91282CMM00",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0019",
    "name": "US Treasury Note 4.00% 2030-02-28",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4,
    "maturity": "2030-02-28",
    "price": null,
    "ytm": 4.25,
    "duration": 3.26,
    "sector": "Treasury",
    "cusip": "91282CGQ8",
    "isin": "US91282CGQ87",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0020",
    "name": "US Treasury Note 4.25% 2034-11-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.25,
    "maturity": "2034-11-15",
    "price": null,
    "ytm": 4.56,
    "duration": 6.9,
    "sector": "Treasury",
    "cusip": "91282CLW9",
    "isin": "US91282CLW90",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0021",
    "name": "US Treasury Note 4.38% 2034-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.38,
    "maturity": "2034-05-15",
    "price": null,
    "ytm": 4.52,
    "duration": 6.53,
    "sector": "Treasury",
    "cusip": "91282CKQ3",
    "isin": "US91282CKQ32",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0022",
    "name": "US Treasury Note 4.13% 2036-02-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.13,
    "maturity": "2036-02-15",
    "price": null,
    "ytm": 4.63,
    "duration": 7.74,
    "sector": "Treasury",
    "cusip": "91282CPZ8",
    "isin": "US91282CPZ85",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0023",
    "name": "US Treasury Note 3.88% 2034-08-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.88,
    "maturity": "2034-08-15",
    "price": null,
    "ytm": 4.54,
    "duration": 6.77,
    "sector": "Treasury",
    "cusip": "91282CLF6",
    "isin": "US91282CLF67",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0024",
    "name": "US Treasury Note 4.25% 2035-08-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.25,
    "maturity": "2035-08-15",
    "price": null,
    "ytm": 4.6,
    "duration": 7.37,
    "sector": "Treasury",
    "cusip": "91282CNT4",
    "isin": "US91282CNT44",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0025",
    "name": "US Treasury Note 4.25% 2035-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.25,
    "maturity": "2035-05-15",
    "price": null,
    "ytm": 4.59,
    "duration": 7.24,
    "sector": "Treasury",
    "cusip": "91282CNC1",
    "isin": "US91282CNC19",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0026",
    "name": "US Treasury Note 4.50% 2033-11-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.5,
    "maturity": "2033-11-15",
    "price": null,
    "ytm": 4.49,
    "duration": 6.16,
    "sector": "Treasury",
    "cusip": "91282CJJ1",
    "isin": "US91282CJJ18",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0027",
    "name": "US Treasury Note 4.00% 2034-02-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4,
    "maturity": "2034-02-15",
    "price": null,
    "ytm": 4.51,
    "duration": 6.39,
    "sector": "Treasury",
    "cusip": "91282CJZ5",
    "isin": "US91282CJZ59",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0028",
    "name": "US Treasury Note 4.00% 2035-11-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4,
    "maturity": "2035-11-15",
    "price": null,
    "ytm": 4.61,
    "duration": 7.64,
    "sector": "Treasury",
    "cusip": "91282CPJ4",
    "isin": "US91282CPJ44",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0029",
    "name": "US Treasury Note 3.88% 2028-07-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.88,
    "maturity": "2028-07-15",
    "price": null,
    "ytm": 4.16,
    "duration": 1.82,
    "sector": "Treasury",
    "cusip": "91282CNM9",
    "isin": "US91282CNM90",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0030",
    "name": "US Treasury Bond 4.38% 2036-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Bond",
    "coupon": 4.38,
    "maturity": "2036-05-15",
    "price": null,
    "ytm": 4.64,
    "duration": 7.87,
    "sector": "Treasury",
    "cusip": "91282CQQ7",
    "isin": "US91282CQQ77",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0031",
    "name": "US Treasury Note 3.88% 2028-06-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.88,
    "maturity": "2028-06-15",
    "price": null,
    "ytm": 4.15,
    "duration": 1.74,
    "sector": "Treasury",
    "cusip": "91282CNH0",
    "isin": "US91282CNH06",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0032",
    "name": "US Treasury Note 3.88% 2033-08-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.88,
    "maturity": "2033-08-15",
    "price": null,
    "ytm": 4.48,
    "duration": 6.04,
    "sector": "Treasury",
    "cusip": "91282CHT1",
    "isin": "US91282CHT18",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0033",
    "name": "US Treasury Note 3.63% 2028-08-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.63,
    "maturity": "2028-08-15",
    "price": null,
    "ytm": 4.16,
    "duration": 1.9,
    "sector": "Treasury",
    "cusip": "91282CNU1",
    "isin": "US91282CNU17",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0034",
    "name": "US Treasury Note 2.88% 2032-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 2.88,
    "maturity": "2032-05-15",
    "price": null,
    "ytm": 4.39,
    "duration": 5.22,
    "sector": "Treasury",
    "cusip": "91282CEP2",
    "isin": "US91282CEP23",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0035",
    "name": "US Treasury Note 3.63% 2030-08-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.63,
    "maturity": "2030-08-31",
    "price": null,
    "ytm": 4.29,
    "duration": 3.71,
    "sector": "Treasury",
    "cusip": "91282CNX5",
    "isin": "US91282CNX55",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0036",
    "name": "US Treasury Note 4.13% 2031-05-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.13,
    "maturity": "2031-05-31",
    "price": null,
    "ytm": 4.31,
    "duration": 4.28,
    "sector": "Treasury",
    "cusip": "91282CQU8",
    "isin": "US91282CQU89",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0037",
    "name": "US Treasury Bond 5.00% 2056-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Bond",
    "coupon": 5,
    "maturity": "2056-05-15",
    "price": null,
    "ytm": 5.21,
    "duration": 15.24,
    "sector": "Treasury",
    "cusip": "912810UU0",
    "isin": "US912810UU06",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0038",
    "name": "US Treasury Note 3.50% 2033-02-28",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.5,
    "maturity": "2033-02-28",
    "price": null,
    "ytm": 4.3,
    "duration": 5.76,
    "sector": "Treasury",
    "cusip": "91282CQD6",
    "isin": "US91282CQD64",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0039",
    "name": "US Treasury Note 3.50% 2033-02-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.5,
    "maturity": "2033-02-15",
    "price": null,
    "ytm": 4.44,
    "duration": 5.72,
    "sector": "Treasury",
    "cusip": "91282CGM7",
    "isin": "US91282CGM73",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0040",
    "name": "US Treasury Note 3.50% 2028-01-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.5,
    "maturity": "2028-01-31",
    "price": null,
    "ytm": 4.12,
    "duration": 1.4,
    "sector": "Treasury",
    "cusip": "91282CGH8",
    "isin": "US91282CGH88",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0041",
    "name": "US Treasury Note 3.63% 2030-12-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.63,
    "maturity": "2030-12-31",
    "price": null,
    "ytm": 4.3,
    "duration": 3.98,
    "sector": "Treasury",
    "cusip": "91282CPR6",
    "isin": "US91282CPR69",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0042",
    "name": "US Treasury Note 3.38% 2028-09-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.38,
    "maturity": "2028-09-15",
    "price": null,
    "ytm": 4.16,
    "duration": 1.99,
    "sector": "Treasury",
    "cusip": "91282CNY3",
    "isin": "US91282CNY39",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0043",
    "name": "US Treasury Note 3.88% 2031-03-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.88,
    "maturity": "2031-03-31",
    "price": null,
    "ytm": 4.31,
    "duration": 4.19,
    "sector": "Treasury",
    "cusip": "91282CQG9",
    "isin": "US91282CQG95",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0044",
    "name": "US Treasury Note 4.00% 2030-05-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4,
    "maturity": "2030-05-31",
    "price": null,
    "ytm": 4.27,
    "duration": 3.46,
    "sector": "Treasury",
    "cusip": "91282CNG2",
    "isin": "US91282CNG23",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0045",
    "name": "US Treasury Note 1.88% 2032-02-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 1.88,
    "maturity": "2032-02-15",
    "price": null,
    "ytm": 4.38,
    "duration": 5.12,
    "sector": "Treasury",
    "cusip": "91282CDY4",
    "isin": "US91282CDY49",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0046",
    "name": "US Treasury Note 3.88% 2030-06-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.88,
    "maturity": "2030-06-30",
    "price": null,
    "ytm": 4.28,
    "duration": 3.54,
    "sector": "Treasury",
    "cusip": "91282CNK3",
    "isin": "US91282CNK35",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0047",
    "name": "US Treasury Note 3.63% 2030-09-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.63,
    "maturity": "2030-09-30",
    "price": null,
    "ytm": 4.29,
    "duration": 3.79,
    "sector": "Treasury",
    "cusip": "91282CPA3",
    "isin": "US91282CPA35",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0048",
    "name": "US Treasury Note 4.13% 2032-11-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.13,
    "maturity": "2032-11-15",
    "price": null,
    "ytm": 4.42,
    "duration": 5.47,
    "sector": "Treasury",
    "cusip": "91282CFV8",
    "isin": "US91282CFV81",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0049",
    "name": "US Treasury Note 3.63% 2030-10-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.63,
    "maturity": "2030-10-31",
    "price": null,
    "ytm": 4.29,
    "duration": 3.87,
    "sector": "Treasury",
    "cusip": "91282CPD7",
    "isin": "US91282CPD73",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0050",
    "name": "US Treasury Note 2.75% 2032-08-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 2.75,
    "maturity": "2032-08-15",
    "price": null,
    "ytm": 4.41,
    "duration": 5.42,
    "sector": "Treasury",
    "cusip": "91282CFF3",
    "isin": "US91282CFF32",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0051",
    "name": "US Treasury Note 4.13% 2031-06-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.13,
    "maturity": "2031-06-30",
    "price": null,
    "ytm": 4.32,
    "duration": 4.35,
    "sector": "Treasury",
    "cusip": "91282CQX2",
    "isin": "US91282CQX29",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0052",
    "name": "US Treasury Note 3.50% 2030-11-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.5,
    "maturity": "2030-11-30",
    "price": null,
    "ytm": 4.3,
    "duration": 3.91,
    "sector": "Treasury",
    "cusip": "91282CPN5",
    "isin": "US91282CPN55",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0053",
    "name": "US Treasury Note 3.75% 2031-01-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.75,
    "maturity": "2031-01-31",
    "price": null,
    "ytm": 4.31,
    "duration": 4.05,
    "sector": "Treasury",
    "cusip": "91282CPW5",
    "isin": "US91282CPW54",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0054",
    "name": "US Treasury Note 3.38% 2027-11-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.38,
    "maturity": "2027-11-30",
    "price": null,
    "ytm": 4.1,
    "duration": 1.24,
    "sector": "Treasury",
    "cusip": "91282CPL9",
    "isin": "US91282CPL99",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0055",
    "name": "US Treasury Bond 5.00% 2055-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Bond",
    "coupon": 5,
    "maturity": "2055-05-15",
    "price": null,
    "ytm": 5.23,
    "duration": 14.99,
    "sector": "Treasury",
    "cusip": "912810UM8",
    "isin": "US912810UM89",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0056",
    "name": "US Treasury Note 3.75% 2027-08-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.75,
    "maturity": "2027-08-15",
    "price": null,
    "ytm": 4.07,
    "duration": 0.97,
    "sector": "Treasury",
    "cusip": "91282CLG4",
    "isin": "US91282CLG41",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0057",
    "name": "US Treasury Note 3.88% 2030-07-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.88,
    "maturity": "2030-07-31",
    "price": null,
    "ytm": 4.28,
    "duration": 3.62,
    "sector": "Treasury",
    "cusip": "91282CNN7",
    "isin": "US91282CNN73",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0058",
    "name": "US Treasury Note 4.25% 2030-01-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.25,
    "maturity": "2030-01-31",
    "price": null,
    "ytm": 4.26,
    "duration": 3.18,
    "sector": "Treasury",
    "cusip": "91282CMG3",
    "isin": "US91282CMG32",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0059",
    "name": "US Treasury Note 3.75% 2028-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 3.75,
    "maturity": "2028-05-15",
    "price": null,
    "ytm": 4.14,
    "duration": 1.68,
    "sector": "Treasury",
    "cusip": "91282CND9",
    "isin": "US91282CND91",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0060",
    "name": "US Treasury Note 4.25% 2029-02-28",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.25,
    "maturity": "2029-02-28",
    "price": null,
    "ytm": 4.19,
    "duration": 2.38,
    "sector": "Treasury",
    "cusip": "91282CKD2",
    "isin": "US91282CKD29",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0061",
    "name": "US Treasury Note 4.25% 2029-06-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.25,
    "maturity": "2029-06-30",
    "price": null,
    "ytm": 4.22,
    "duration": 2.67,
    "sector": "Treasury",
    "cusip": "91282CKX8",
    "isin": "US91282CKX82",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0062",
    "name": "US Treasury Note 4.00% 2030-03-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4,
    "maturity": "2030-03-31",
    "price": null,
    "ytm": 4.26,
    "duration": 3.34,
    "sector": "Treasury",
    "cusip": "91282CMU2",
    "isin": "US91282CMU26",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0063",
    "name": "US Treasury Note 4.13% 2029-11-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4.13,
    "maturity": "2029-11-30",
    "price": null,
    "ytm": 4.24,
    "duration": 3.03,
    "sector": "Treasury",
    "cusip": "91282CMA6",
    "isin": "US91282CMA61",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0064",
    "name": "US Treasury Note 4.00% 2027-12-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Note",
    "coupon": 4,
    "maturity": "2027-12-15",
    "price": null,
    "ytm": 4.1,
    "duration": 1.28,
    "sector": "Treasury",
    "cusip": "91282CMB4",
    "isin": "US91282CMB45",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0065",
    "name": "US Treasury Bond 4.75% 2055-08-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Treasury Bond",
    "coupon": 4.75,
    "maturity": "2055-08-15",
    "price": null,
    "ytm": 5.24,
    "duration": 15.12,
    "sector": "Treasury",
    "cusip": "912810UK2",
    "isin": "US912810UK24",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0066",
    "name": "FHLMC Reference Note 6.25% 2032-07-15",
    "govCorp": "Government-Related",
    "govCorpRaw": "Government-Related (Agency/MBS)",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "FHLMC Reference Note",
    "coupon": 6.25,
    "maturity": "2032-07-15",
    "price": null,
    "ytm": 4.41,
    "duration": 4.96,
    "sector": "Agency",
    "cusip": "3134A4KX1",
    "isin": "US3134A4KX12",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0067",
    "name": "GNMA2 30YR Pool 2.50% 2051-05-20",
    "govCorp": "Government-Related",
    "govCorpRaw": "Government-Related (Agency/MBS)",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "GNMA2 30YR Pool",
    "coupon": 2.5,
    "maturity": "2051-05-20",
    "price": null,
    "ytm": 5.14,
    "duration": 16.2,
    "sector": "MBS Pass-Through",
    "cusip": "36179WFG8",
    "isin": "US36179WFG87",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0068",
    "name": "FNMA 30YR UMBS Pool 2.00% 2051-10-01",
    "govCorp": "Government-Related",
    "govCorpRaw": "Government-Related (Agency/MBS)",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "FNMA 30YR UMBS Pool",
    "coupon": 2,
    "maturity": "2051-10-01",
    "price": null,
    "ytm": 5.22,
    "duration": 17.18,
    "sector": "MBS Pass-Through",
    "cusip": "31418D4X7",
    "isin": "US31418D4X74",
    "sourceEtf": "AGG"
  },
  {
    "id": "BND-0069",
    "name": "Anheuser-Busch Companies LLC 4.90% 2046-02-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Belgium",
    "currency": "USD",
    "issuer": "Anheuser-Busch Companies LLC",
    "coupon": 4.9,
    "maturity": "2046-02-01",
    "price": 87.84,
    "ytm": 5.96,
    "duration": 11.9,
    "sector": "Consumer Non-Cyclical",
    "cusip": "03522AAJ9",
    "isin": "US03522AAJ97",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0070",
    "name": "CVS Health Corp 5.05% 2048-03-25",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "CVS Health Corp",
    "coupon": 5.05,
    "maturity": "2048-03-25",
    "price": 84.93,
    "ytm": 6.34,
    "duration": 12.29,
    "sector": "Consumer Non-Cyclical",
    "cusip": "126650CZ1",
    "isin": "US126650CZ11",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0071",
    "name": "Meta Platforms Inc 4.88% 2035-11-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Meta Platforms Inc",
    "coupon": 4.88,
    "maturity": "2035-11-15",
    "price": 94.77,
    "ytm": 5.62,
    "duration": 7.33,
    "sector": "Communications",
    "cusip": "30303MAD4",
    "isin": "US30303MAD48",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0072",
    "name": "Space Exploration Technologies Corp (144A) 5.35% 2031-07-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Space Exploration Technologies Corp (144A)",
    "coupon": 5.35,
    "maturity": "2031-07-15",
    "price": 98.58,
    "ytm": 5.68,
    "duration": 4.25,
    "sector": "Communications",
    "cusip": "84615QAA1",
    "isin": "US84615QAA13",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0073",
    "name": "T-Mobile USA Inc 3.88% 2030-04-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "T-Mobile USA Inc",
    "coupon": 3.88,
    "maturity": "2030-04-15",
    "price": 96.48,
    "ytm": 4.93,
    "duration": 3.37,
    "sector": "Communications",
    "cusip": "87264ABF1",
    "isin": "US87264ABF12",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0074",
    "name": "Amazon.com Inc 4.88% 2036-03-13",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Amazon.com Inc",
    "coupon": 4.88,
    "maturity": "2036-03-13",
    "price": 95.93,
    "ytm": 5.42,
    "duration": 7.52,
    "sector": "Consumer Cyclical",
    "cusip": "023135DF0",
    "isin": "US023135DF00",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0075",
    "name": "Goldman Sachs Group Inc/The 6.75% 2037-10-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Goldman Sachs Group Inc/The",
    "coupon": 6.75,
    "maturity": "2037-10-01",
    "price": 106.61,
    "ytm": 5.93,
    "duration": 7.9,
    "sector": "Banking",
    "cusip": "38141GFD1",
    "isin": "US38141GFD16",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0076",
    "name": "Charter Communications Operating LLC (144A) 7.09% 2038-09-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Charter Communications Operating LLC (144A)",
    "coupon": 7.09,
    "maturity": "2038-09-01",
    "price": 99.29,
    "ytm": 7.17,
    "duration": 8.0,
    "sector": "Communications",
    "cusip": "161175CU6",
    "isin": "US161175CU68",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0077",
    "name": "Boeing Co 5.80% 2050-05-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Boeing Co",
    "coupon": 5.8,
    "maturity": "2050-05-01",
    "price": 94.9,
    "ytm": 6.22,
    "duration": 12.55,
    "sector": "Capital Goods",
    "cusip": "097023CW3",
    "isin": "US097023CW33",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0078",
    "name": "Pfizer Investment Enterprises Pte 5.30% 2053-05-19",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Pfizer Investment Enterprises Pte",
    "coupon": 5.3,
    "maturity": "2053-05-19",
    "price": 89.48,
    "ytm": 6.1,
    "duration": 13.41,
    "sector": "Consumer Non-Cyclical",
    "cusip": "716973AG7",
    "isin": "US716973AG71",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0079",
    "name": "Bank of America Corp MTN 5.47% 2035-01-23",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Bank of America Corp MTN",
    "coupon": 5.47,
    "maturity": "2035-01-23",
    "price": 100.84,
    "ytm": 5.33,
    "duration": 6.69,
    "sector": "Banking",
    "cusip": "06051GMA4",
    "isin": "US06051GMA49",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0080",
    "name": "Wells Fargo & Company MTN 5.01% 2051-04-04",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Wells Fargo & Company MTN",
    "coupon": 5.01,
    "maturity": "2051-04-04",
    "price": 86.24,
    "ytm": 6.16,
    "duration": 13.18,
    "sector": "Banking",
    "cusip": "95000U2M4",
    "isin": "US95000U2M49",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0081",
    "name": "AbbVie Inc 3.20% 2029-11-21",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "AbbVie Inc",
    "coupon": 3.2,
    "maturity": "2029-11-21",
    "price": 95.68,
    "ytm": 4.64,
    "duration": 3.04,
    "sector": "Consumer Non-Cyclical",
    "cusip": "00287YBX6",
    "isin": "US00287YBX67",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0082",
    "name": "AT&T Inc 3.50% 2053-09-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "AT&T Inc",
    "coupon": 3.5,
    "maturity": "2053-09-15",
    "price": 60.96,
    "ytm": 6.62,
    "duration": 14.36,
    "sector": "Communications",
    "cusip": "00206RKJ0",
    "isin": "US00206RKJ04",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0083",
    "name": "Oracle Corporation 5.70% 2036-02-04",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Oracle Corporation",
    "coupon": 5.7,
    "maturity": "2036-02-04",
    "price": 93.7,
    "ytm": 6.6,
    "duration": 7.13,
    "sector": "Technology",
    "cusip": "68389XDZ5",
    "isin": "US68389XDZ50",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0084",
    "name": "Salesforce Inc 5.55% 2036-03-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Salesforce Inc",
    "coupon": 5.55,
    "maturity": "2036-03-15",
    "price": 98.03,
    "ytm": 5.82,
    "duration": 7.33,
    "sector": "Technology",
    "cusip": "79466LAU8",
    "isin": "US79466LAU89",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0085",
    "name": "JPMorgan Chase & Co 5.35% 2034-06-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "JPMorgan Chase & Co",
    "coupon": 5.35,
    "maturity": "2034-06-01",
    "price": 100.72,
    "ytm": 5.25,
    "duration": 6.28,
    "sector": "Banking",
    "cusip": "46647PDR4",
    "isin": "US46647PDR47",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0086",
    "name": "Morgan Stanley MTN 5.30% 2037-04-10",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Morgan Stanley MTN",
    "coupon": 5.3,
    "maturity": "2037-04-10",
    "price": 97.56,
    "ytm": 5.6,
    "duration": 8.04,
    "sector": "Banking",
    "cusip": "61748UAX0",
    "isin": "US61748UAX00",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0087",
    "name": "Deutsche Telekom International Finance 8.25% 2030-06-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Germany",
    "currency": "USD",
    "issuer": "Deutsche Telekom International Finance",
    "coupon": 8.25,
    "maturity": "2030-06-15",
    "price": 111.47,
    "ytm": 4.93,
    "duration": 3.29,
    "sector": "Communications",
    "cusip": "25156PAC7",
    "isin": "US25156PAC77",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0088",
    "name": "Alphabet Inc 6.38% 2056-08-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Alphabet Inc",
    "coupon": 6.38,
    "maturity": "2056-08-15",
    "price": 101.39,
    "ytm": 6.27,
    "duration": 13.4,
    "sector": "Technology",
    "cusip": "02079KCU9",
    "isin": "US02079KCU97",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0089",
    "name": "Verizon Communications Inc 2.36% 2032-03-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Verizon Communications Inc",
    "coupon": 2.36,
    "maturity": "2032-03-15",
    "price": 87.01,
    "ytm": 5.05,
    "duration": 5.11,
    "sector": "Communications",
    "cusip": "92343VGN8",
    "isin": "US92343VGN82",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0090",
    "name": "Citigroup Inc 4.41% 2031-03-31",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Citigroup Inc",
    "coupon": 4.41,
    "maturity": "2031-03-31",
    "price": 98.22,
    "ytm": 5.46,
    "duration": 4.12,
    "sector": "Banking",
    "cusip": "172967MP3",
    "isin": "US172967MP39",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0091",
    "name": "Amgen Inc 5.65% 2053-03-02",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Amgen Inc",
    "coupon": 5.65,
    "maturity": "2053-03-02",
    "price": 93.21,
    "ytm": 6.17,
    "duration": 13.22,
    "sector": "Consumer Non-Cyclical",
    "cusip": "031162DT4",
    "isin": "US031162DT45",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0092",
    "name": "Home Depot Inc 5.88% 2036-12-16",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Home Depot Inc",
    "coupon": 5.88,
    "maturity": "2036-12-16",
    "price": 104.39,
    "ytm": 5.32,
    "duration": 7.71,
    "sector": "Consumer Cyclical",
    "cusip": "437076AS1",
    "isin": "US437076AS19",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0093",
    "name": "British Telecommunications Plc 9.63% 2030-12-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "British Telecommunications Plc",
    "coupon": 9.63,
    "maturity": "2030-12-15",
    "price": 117.44,
    "ytm": 5.09,
    "duration": 3.59,
    "sector": "Communications",
    "cusip": "111021AE1",
    "isin": "US111021AE12",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0094",
    "name": "HSBC Holdings Plc 5.28% 2037-03-10",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "HSBC Holdings Plc",
    "coupon": 5.28,
    "maturity": "2037-03-10",
    "price": 97,
    "ytm": 5.65,
    "duration": 7.98,
    "sector": "Banking",
    "cusip": "404280FM6",
    "isin": "US404280FM61",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0095",
    "name": "HSBC Holdings Plc 5.40% 2033-08-11",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "HSBC Holdings Plc",
    "coupon": 5.4,
    "maturity": "2033-08-11",
    "price": 100.61,
    "ytm": 5.43,
    "duration": 5.75,
    "sector": "Banking",
    "cusip": "404280DH9",
    "isin": "US404280DH94",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0096",
    "name": "Barclays Plc 7.44% 2033-11-02",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "Barclays Plc",
    "coupon": 7.44,
    "maturity": "2033-11-02",
    "price": 110.56,
    "ytm": 5.64,
    "duration": 5.67,
    "sector": "Banking",
    "cusip": "06738ECE3",
    "isin": "US06738ECE32",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0097",
    "name": "Barclays Plc 5.59% 2036-06-26",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "Barclays Plc",
    "coupon": 5.59,
    "maturity": "2036-06-26",
    "price": 98.26,
    "ytm": 5.79,
    "duration": 7.45,
    "sector": "Banking",
    "cusip": "06738EDN2",
    "isin": "US06738EDN22",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0098",
    "name": "Lloyds Banking Group Plc 5.68% 2035-01-05",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "Lloyds Banking Group Plc",
    "coupon": 5.68,
    "maturity": "2035-01-05",
    "price": 101.35,
    "ytm": 5.5,
    "duration": 6.6,
    "sector": "Banking",
    "cusip": "53944YAX1",
    "isin": "US53944YAX13",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0099",
    "name": "BAT Capital Corp 4.39% 2037-08-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "BAT Capital Corp",
    "coupon": 4.39,
    "maturity": "2037-08-15",
    "price": 89.81,
    "ytm": 5.65,
    "duration": 8.45,
    "sector": "Consumer Non-Cyclical",
    "cusip": "05526DBD6",
    "isin": "US05526DBD66",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0100",
    "name": "GlaxoSmithKline Capital Inc 6.38% 2038-05-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "GlaxoSmithKline Capital Inc",
    "coupon": 6.38,
    "maturity": "2038-05-15",
    "price": 107.83,
    "ytm": 5.46,
    "duration": 8.4,
    "sector": "Consumer Non-Cyclical",
    "cusip": "377372AE7",
    "isin": "US377372AE71",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0101",
    "name": "AstraZeneca Plc 6.45% 2037-09-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "AstraZeneca Plc",
    "coupon": 6.45,
    "maturity": "2037-09-15",
    "price": 108.4,
    "ytm": 5.43,
    "duration": 8.02,
    "sector": "Consumer Non-Cyclical",
    "cusip": "046353AD0",
    "isin": "US046353AD01",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0102",
    "name": "BP Capital Markets America Inc 4.81% 2033-02-13",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "UK",
    "country": "United Kingdom",
    "currency": "USD",
    "issuer": "BP Capital Markets America Inc",
    "coupon": 4.81,
    "maturity": "2033-02-13",
    "price": 98.49,
    "ytm": 5.09,
    "duration": 5.51,
    "sector": "Energy",
    "cusip": "10373QBU3",
    "isin": "US10373QBU31",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0103",
    "name": "Novartis Capital Corp 4.90% 2036-03-18",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Switzerland",
    "currency": "USD",
    "issuer": "Novartis Capital Corp",
    "coupon": 4.9,
    "maturity": "2036-03-18",
    "price": 97.55,
    "ytm": 5.23,
    "duration": 7.55,
    "sector": "Consumer Non-Cyclical",
    "cusip": "66989HBJ6",
    "isin": "US66989HBJ68",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0104",
    "name": "Novartis Capital Corp 4.60% 2033-03-18",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Switzerland",
    "currency": "USD",
    "issuer": "Novartis Capital Corp",
    "coupon": 4.6,
    "maturity": "2033-03-18",
    "price": 98.08,
    "ytm": 4.94,
    "duration": 5.62,
    "sector": "Consumer Non-Cyclical",
    "cusip": "66989HBH0",
    "isin": "US66989HBH03",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0105",
    "name": "Anheuser-Busch InBev Worldwide Inc 5.55% 2049-01-23",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Belgium",
    "currency": "USD",
    "issuer": "Anheuser-Busch InBev Worldwide Inc",
    "coupon": 5.55,
    "maturity": "2049-01-23",
    "price": 94.74,
    "ytm": 5.98,
    "duration": 12.44,
    "sector": "Consumer Non-Cyclical",
    "cusip": "03523TBV9",
    "isin": "US03523TBV98",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0106",
    "name": "Anheuser-Busch InBev Worldwide Inc 5.45% 2039-01-23",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Belgium",
    "currency": "USD",
    "issuer": "Anheuser-Busch InBev Worldwide Inc",
    "coupon": 5.45,
    "maturity": "2039-01-23",
    "price": 99.43,
    "ytm": 5.51,
    "duration": 8.92,
    "sector": "Consumer Non-Cyclical",
    "cusip": "03523TBU1",
    "isin": "US03523TBU16",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0107",
    "name": "Telefonica Emisiones SAU 7.04% 2036-06-20",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Spain",
    "currency": "USD",
    "issuer": "Telefonica Emisiones SAU",
    "coupon": 7.04,
    "maturity": "2036-06-20",
    "price": 108.67,
    "ytm": 5.87,
    "duration": 7.14,
    "sector": "Communications",
    "cusip": "87938WAC7",
    "isin": "US87938WAC73",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0108",
    "name": "Telefonica Emisiones SAU 5.21% 2047-03-08",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Spain",
    "currency": "USD",
    "issuer": "Telefonica Emisiones SAU",
    "coupon": 5.21,
    "maturity": "2047-03-08",
    "price": 85.6,
    "ytm": 6.49,
    "duration": 11.82,
    "sector": "Communications",
    "cusip": "87938WAU7",
    "isin": "US87938WAU71",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0109",
    "name": "Banco Santander SA 6.92% 2033-08-08",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Europe",
    "country": "Spain",
    "currency": "USD",
    "issuer": "Banco Santander SA",
    "coupon": 6.92,
    "maturity": "2033-08-08",
    "price": 107.18,
    "ytm": 5.66,
    "duration": 5.54,
    "sector": "Banking",
    "cusip": "05964HAV7",
    "isin": "US05964HAV78",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0110",
    "name": "BHP Billiton Finance (USA) Ltd 5.00% 2043-09-30",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Asia-Pacific",
    "country": "Australia",
    "currency": "USD",
    "issuer": "BHP Billiton Finance (USA) Ltd",
    "coupon": 5,
    "maturity": "2043-09-30",
    "price": 91.07,
    "ytm": 5.8,
    "duration": 11.13,
    "sector": "Basic Industry",
    "cusip": "055451AV0",
    "isin": "US055451AV01",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0111",
    "name": "Takeda Pharmaceutical Co Ltd 2.05% 2030-03-31",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "Asia-Pacific",
    "country": "Japan",
    "currency": "USD",
    "issuer": "Takeda Pharmaceutical Co Ltd",
    "coupon": 2.05,
    "maturity": "2030-03-31",
    "price": 90.83,
    "ytm": 4.83,
    "duration": 3.42,
    "sector": "Consumer Non-Cyclical",
    "cusip": "874060AX4",
    "isin": "US874060AX48",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0112",
    "name": "Enbridge Inc 5.70% 2033-03-08",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "Canada",
    "currency": "USD",
    "issuer": "Enbridge Inc",
    "coupon": 5.7,
    "maturity": "2033-03-08",
    "price": 102.49,
    "ytm": 5.25,
    "duration": 5.44,
    "sector": "Energy",
    "cusip": "29250NBR5",
    "isin": "US29250NBR52",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0113",
    "name": "Toronto-Dominion Bank/The MTN 4.46% 2032-06-08",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "Canada",
    "currency": "USD",
    "issuer": "Toronto-Dominion Bank/The MTN",
    "coupon": 4.46,
    "maturity": "2032-06-08",
    "price": 97.48,
    "ytm": 4.96,
    "duration": 5.03,
    "sector": "Banking",
    "cusip": "89115A2E1",
    "isin": "US89115A2E11",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0114",
    "name": "Royal Bank of Canada MTN 4.65% 2030-10-18",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "Canada",
    "currency": "USD",
    "issuer": "Royal Bank of Canada MTN",
    "coupon": 4.65,
    "maturity": "2030-10-18",
    "price": 99.48,
    "ytm": 4.81,
    "duration": 3.76,
    "sector": "Banking",
    "cusip": "78017FZT3",
    "isin": "US78017FZT38",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0115",
    "name": "Apple Inc 4.65% 2046-02-23",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Apple Inc",
    "coupon": 4.65,
    "maturity": "2046-02-23",
    "price": 86.91,
    "ytm": 5.78,
    "duration": 12.16,
    "sector": "Technology",
    "cusip": "037833BX7",
    "isin": "US037833BX70",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0116",
    "name": "Apple Inc 1.65% 2030-05-11",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Apple Inc",
    "coupon": 1.65,
    "maturity": "2030-05-11",
    "price": 90.27,
    "ytm": 4.5,
    "duration": 3.56,
    "sector": "Technology",
    "cusip": "037833DU1",
    "isin": "US037833DU14",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0117",
    "name": "Microsoft Corporation 2.52% 2050-06-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Microsoft Corporation",
    "coupon": 2.52,
    "maturity": "2050-06-01",
    "price": 56.5,
    "ytm": 5.97,
    "duration": 15.19,
    "sector": "Technology",
    "cusip": "594918CC6",
    "isin": "US594918CC64",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0118",
    "name": "Nvidia Corporation 4.95% 2036-06-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Nvidia Corporation",
    "coupon": 4.95,
    "maturity": "2036-06-15",
    "price": 95.9,
    "ytm": 5.49,
    "duration": 7.61,
    "sector": "Technology",
    "cusip": "67066GAT1",
    "isin": "US67066GAT13",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0119",
    "name": "Broadcom Inc 3.14% 2035-11-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Broadcom Inc",
    "coupon": 3.14,
    "maturity": "2035-11-15",
    "price": 81.72,
    "ytm": 5.73,
    "duration": 7.76,
    "sector": "Technology",
    "cusip": "11135FBM2",
    "isin": "US11135FBM23",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0120",
    "name": "Visa Inc 4.30% 2045-12-14",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Visa Inc",
    "coupon": 4.3,
    "maturity": "2045-12-14",
    "price": 82.93,
    "ytm": 5.78,
    "duration": 12.24,
    "sector": "Technology",
    "cusip": "92826CAF9",
    "isin": "US92826CAF95",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0121",
    "name": "Cisco Systems Inc 4.95% 2031-02-26",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Cisco Systems Inc",
    "coupon": 4.95,
    "maturity": "2031-02-26",
    "price": 101.02,
    "ytm": 4.7,
    "duration": 4.02,
    "sector": "Technology",
    "cusip": "17275RBS0",
    "isin": "US17275RBS04",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0122",
    "name": "International Business Machines Corp 4.25% 2049-05-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "International Business Machines Corp",
    "coupon": 4.25,
    "maturity": "2049-05-15",
    "price": 73.19,
    "ytm": 6.53,
    "duration": 12.98,
    "sector": "Technology",
    "cusip": "459200KC4",
    "isin": "US459200KC42",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0123",
    "name": "Intel Corporation 5.20% 2033-02-10",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Intel Corporation",
    "coupon": 5.2,
    "maturity": "2033-02-10",
    "price": 99.86,
    "ytm": 5.22,
    "duration": 5.44,
    "sector": "Technology",
    "cusip": "458140CG3",
    "isin": "US458140CG35",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0124",
    "name": "Synopsys Inc 5.15% 2035-04-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Synopsys Inc",
    "coupon": 5.15,
    "maturity": "2035-04-01",
    "price": 97.73,
    "ytm": 5.48,
    "duration": 6.88,
    "sector": "Technology",
    "cusip": "871607AE7",
    "isin": "US871607AE70",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0125",
    "name": "Comcast Corporation 2.94% 2056-11-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Comcast Corporation",
    "coupon": 2.94,
    "maturity": "2056-11-01",
    "price": 51.08,
    "ytm": 6.75,
    "duration": 15.34,
    "sector": "Communications",
    "cusip": "20030NDU2",
    "isin": "US20030NDU28",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0126",
    "name": "Walt Disney Co 2.65% 2031-01-13",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Walt Disney Co",
    "coupon": 2.65,
    "maturity": "2031-01-13",
    "price": 92.14,
    "ytm": 4.64,
    "duration": 4.08,
    "sector": "Communications",
    "cusip": "254687FX9",
    "isin": "US254687FX90",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0127",
    "name": "Ford Motor Company 3.25% 2032-02-12",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Ford Motor Company",
    "coupon": 3.25,
    "maturity": "2032-02-12",
    "price": 88.12,
    "ytm": 5.81,
    "duration": 4.89,
    "sector": "Consumer Cyclical",
    "cusip": "345370DA5",
    "isin": "US345370DA55",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0128",
    "name": "Exxon Mobil Corp 2.61% 2030-10-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Exxon Mobil Corp",
    "coupon": 2.61,
    "maturity": "2030-10-15",
    "price": 92.79,
    "ytm": 4.52,
    "duration": 3.88,
    "sector": "Energy",
    "cusip": "30231GBN1",
    "isin": "US30231GBN16",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0129",
    "name": "Occidental Petroleum Corporation 6.45% 2036-09-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Occidental Petroleum Corporation",
    "coupon": 6.45,
    "maturity": "2036-09-15",
    "price": 106.75,
    "ytm": 5.57,
    "duration": 7.47,
    "sector": "Energy",
    "cusip": "674599DF9",
    "isin": "US674599DF90",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0130",
    "name": "Shell Finance US Inc 4.38% 2045-05-11",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Shell Finance US Inc",
    "coupon": 4.38,
    "maturity": "2045-05-11",
    "price": 82.46,
    "ytm": 5.94,
    "duration": 12.02,
    "sector": "Energy",
    "cusip": "822905AA3",
    "isin": "US822905AA35",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0131",
    "name": "Baker Hughes Holdings LLC 5.00% 2036-06-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Baker Hughes Holdings LLC",
    "coupon": 5,
    "maturity": "2036-06-15",
    "price": 96.82,
    "ytm": 5.42,
    "duration": 7.61,
    "sector": "Energy",
    "cusip": "05724BAP4",
    "isin": "US05724BAP40",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0132",
    "name": "Pacific Gas and Electric Company 4.55% 2030-07-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Pacific Gas and Electric Company",
    "coupon": 4.55,
    "maturity": "2030-07-01",
    "price": 98.23,
    "ytm": 5.05,
    "duration": 3.49,
    "sector": "Electric",
    "cusip": "694308JM0",
    "isin": "US694308JM04",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0133",
    "name": "UnitedHealth Group Inc 5.63% 2054-07-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "UnitedHealth Group Inc",
    "coupon": 5.63,
    "maturity": "2054-07-15",
    "price": 93.14,
    "ytm": 6.14,
    "duration": 13.48,
    "sector": "Insurance",
    "cusip": "91324PFL1",
    "isin": "US91324PFL13",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0134",
    "name": "Berkshire Hathaway Finance Corp 4.20% 2048-08-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Berkshire Hathaway Finance Corp",
    "coupon": 4.2,
    "maturity": "2048-08-15",
    "price": 78.27,
    "ytm": 5.99,
    "duration": 13.1,
    "sector": "Insurance",
    "cusip": "084664CQ2",
    "isin": "US084664CQ25",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0135",
    "name": "Cigna Group 4.90% 2048-12-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Cigna Group",
    "coupon": 4.9,
    "maturity": "2048-12-15",
    "price": 84.78,
    "ytm": 6.16,
    "duration": 12.59,
    "sector": "Consumer Non-Cyclical",
    "cusip": "125523AK6",
    "isin": "US125523AK66",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0136",
    "name": "Bristol-Myers Squibb Co 4.25% 2054-10-26",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Bristol-Myers Squibb Co",
    "coupon": 4.25,
    "maturity": "2054-10-26",
    "price": 77.68,
    "ytm": 6.05,
    "duration": 14.53,
    "sector": "Consumer Non-Cyclical",
    "cusip": "110122CR7",
    "isin": "US110122CR72",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0137",
    "name": "Eli Lilly and Company 4.85% 2036-05-20",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Eli Lilly and Company",
    "coupon": 4.85,
    "maturity": "2036-05-20",
    "price": 97.32,
    "ytm": 5.2,
    "duration": 7.62,
    "sector": "Consumer Non-Cyclical",
    "cusip": "532457DR6",
    "isin": "US532457DR63",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0138",
    "name": "Kroger Co 5.00% 2034-09-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Kroger Co",
    "coupon": 5,
    "maturity": "2034-09-15",
    "price": 97.11,
    "ytm": 5.45,
    "duration": 6.55,
    "sector": "Consumer Non-Cyclical",
    "cusip": "501044DV0",
    "isin": "US501044DV05",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0139",
    "name": "Altria Group Inc 5.95% 2049-02-14",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Altria Group Inc",
    "coupon": 5.95,
    "maturity": "2049-02-14",
    "price": 94.87,
    "ytm": 6.38,
    "duration": 12.03,
    "sector": "Consumer Non-Cyclical",
    "cusip": "02209SBF9",
    "isin": "US02209SBF92",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0140",
    "name": "Philip Morris International Inc 5.13% 2030-02-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Philip Morris International Inc",
    "coupon": 5.13,
    "maturity": "2030-02-15",
    "price": 101.16,
    "ytm": 4.76,
    "duration": 3.17,
    "sector": "Consumer Non-Cyclical",
    "cusip": "718172DA4",
    "isin": "US718172DA46",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0141",
    "name": "HCA Inc 3.50% 2030-09-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "HCA Inc",
    "coupon": 3.5,
    "maturity": "2030-09-01",
    "price": 94.7,
    "ytm": 4.96,
    "duration": 3.71,
    "sector": "Consumer Non-Cyclical",
    "cusip": "404119CA5",
    "isin": "US404119CA57",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0142",
    "name": "Fidelity National Information Services 4.80% 2031-03-10",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Fidelity National Information Services",
    "coupon": 4.8,
    "maturity": "2031-03-10",
    "price": 98.42,
    "ytm": 5.19,
    "duration": 4.05,
    "sector": "Technology",
    "cusip": "31620MCE4",
    "isin": "US31620MCE49",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0143",
    "name": "Global Payments Inc 4.88% 2030-11-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Global Payments Inc",
    "coupon": 4.88,
    "maturity": "2030-11-15",
    "price": 97.73,
    "ytm": 5.48,
    "duration": 3.8,
    "sector": "Technology",
    "cusip": "37940XAW2",
    "isin": "US37940XAW20",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0144",
    "name": "US Bancorp MTN 5.68% 2035-01-23",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "US Bancorp MTN",
    "coupon": 5.68,
    "maturity": "2035-01-23",
    "price": 101.79,
    "ytm": 5.4,
    "duration": 6.64,
    "sector": "Banking",
    "cusip": "91159HJR2",
    "isin": "US91159HJR21",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0145",
    "name": "Truist Financial Corp MTN 5.71% 2035-01-24",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Truist Financial Corp MTN",
    "coupon": 5.71,
    "maturity": "2035-01-24",
    "price": 101.47,
    "ytm": 5.48,
    "duration": 6.63,
    "sector": "Banking",
    "cusip": "89788MAS1",
    "isin": "US89788MAS17",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0146",
    "name": "PNC Financial Services Group Inc 6.88% 2034-10-20",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "PNC Financial Services Group Inc",
    "coupon": 6.88,
    "maturity": "2034-10-20",
    "price": 108.89,
    "ytm": 5.42,
    "duration": 6.34,
    "sector": "Banking",
    "cusip": "693475BU8",
    "isin": "US693475BU84",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0147",
    "name": "Ally Financial Inc 8.00% 2031-11-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Ally Financial Inc",
    "coupon": 8,
    "maturity": "2031-11-01",
    "price": 110.73,
    "ytm": 5.6,
    "duration": 4.32,
    "sector": "Banking",
    "cusip": "36186CBY8",
    "isin": "US36186CBY84",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0148",
    "name": "Northrop Grumman Corp 4.03% 2047-10-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Northrop Grumman Corp",
    "coupon": 4.03,
    "maturity": "2047-10-15",
    "price": 76.48,
    "ytm": 6.01,
    "duration": 13.0,
    "sector": "Capital Goods",
    "cusip": "666807BP6",
    "isin": "US666807BP60",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0149",
    "name": "Honeywell Aerospace Inc 4.95% 2036-03-16",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Honeywell Aerospace Inc",
    "coupon": 4.95,
    "maturity": "2036-03-16",
    "price": 96.63,
    "ytm": 5.4,
    "duration": 7.52,
    "sector": "Capital Goods",
    "cusip": "43849RAR6",
    "isin": "US43849RAR66",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0150",
    "name": "Eaton Corporation 4.80% 2036-03-06",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Eaton Corporation",
    "coupon": 4.8,
    "maturity": "2036-03-06",
    "price": 96.04,
    "ytm": 5.33,
    "duration": 7.54,
    "sector": "Capital Goods",
    "cusip": "278058DZ2",
    "isin": "US278058DZ25",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0151",
    "name": "Wyeth LLC 5.95% 2037-04-01",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Wyeth LLC",
    "coupon": 5.95,
    "maturity": "2037-04-01",
    "price": 103.98,
    "ytm": 5.45,
    "duration": 7.89,
    "sector": "Consumer Non-Cyclical",
    "cusip": "983024AN0",
    "isin": "US983024AN02",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0152",
    "name": "Reynolds American Inc 5.85% 2045-08-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Reynolds American Inc",
    "coupon": 5.85,
    "maturity": "2045-08-15",
    "price": 95.38,
    "ytm": 6.27,
    "duration": 11.17,
    "sector": "Consumer Non-Cyclical",
    "cusip": "761713BB1",
    "isin": "US761713BB19",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0153",
    "name": "Sprint Capital Corporation 8.75% 2032-03-15",
    "govCorp": "Corporate",
    "govCorpRaw": "Corporate",
    "region": "North America",
    "country": "United States",
    "currency": "USD",
    "issuer": "Sprint Capital Corporation",
    "coupon": 8.75,
    "maturity": "2032-03-15",
    "price": 116.77,
    "ytm": 5.25,
    "duration": 4.51,
    "sector": "Communications",
    "cusip": "852060AT9",
    "isin": "US852060AT99",
    "sourceEtf": "LQD"
  },
  {
    "id": "BND-0154",
    "name": "Argentina Republic of Government 4.13% 2035-07-09",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Argentina",
    "currency": "USD",
    "issuer": "Argentina Republic of Government",
    "coupon": 4.13,
    "maturity": "2035-07-09",
    "price": 77.78,
    "ytm": 9.42,
    "duration": 6.84,
    "sector": "Sovereign",
    "cusip": "040114HT0",
    "isin": "US040114HT09",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0155",
    "name": "Argentina Republic of Government 5.00% 2038-01-09",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Argentina",
    "currency": "USD",
    "issuer": "Argentina Republic of Government",
    "coupon": 5,
    "maturity": "2038-01-09",
    "price": 81.2,
    "ytm": 9.32,
    "duration": 7.83,
    "sector": "Sovereign",
    "cusip": "040114HU7",
    "isin": "US040114HU71",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0156",
    "name": "Argentina Republic of Government 0.75% 2030-07-09",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Argentina",
    "currency": "USD",
    "issuer": "Argentina Republic of Government",
    "coupon": 0.75,
    "maturity": "2030-07-09",
    "price": 87.5,
    "ytm": 7.89,
    "duration": 3.69,
    "sector": "Sovereign",
    "cusip": "040114HS2",
    "isin": "US040114HS26",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0157",
    "name": "Argentina Republic of Government 3.50% 2041-07-09",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Argentina",
    "currency": "USD",
    "issuer": "Argentina Republic of Government",
    "coupon": 3.5,
    "maturity": "2041-07-09",
    "price": 72.7,
    "ytm": 9.45,
    "duration": 9.77,
    "sector": "Sovereign",
    "cusip": "040114HV5",
    "isin": "US040114HV54",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0158",
    "name": "Ecuador Republic of (Government) RegS 6.90% 2035-07-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Ecuador",
    "currency": "USD",
    "issuer": "Ecuador Republic of (Government) RegS",
    "coupon": 6.9,
    "maturity": "2035-07-31",
    "price": 90.94,
    "ytm": 8.73,
    "duration": 6.38,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS2214238441",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0159",
    "name": "Ecuador Republic of (Government) RegS 8.75% 2034-01-29",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Ecuador",
    "currency": "USD",
    "issuer": "Ecuador Republic of (Government) RegS",
    "coupon": 8.75,
    "maturity": "2034-01-29",
    "price": 99.88,
    "ytm": 8.77,
    "duration": 5.38,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS3285368620",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0160",
    "name": "Uruguay (Oriental Republic of) 5.10% 2050-06-18",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Uruguay",
    "currency": "USD",
    "issuer": "Uruguay (Oriental Republic of)",
    "coupon": 5.1,
    "maturity": "2050-06-18",
    "price": 89.56,
    "ytm": 5.94,
    "duration": 13.03,
    "sector": "Sovereign",
    "cusip": "760942BA9",
    "isin": "US760942BA98",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0161",
    "name": "Uruguay (Oriental Republic of) 5.75% 2034-10-28",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Uruguay",
    "currency": "USD",
    "issuer": "Uruguay (Oriental Republic of)",
    "coupon": 5.75,
    "maturity": "2034-10-28",
    "price": 103.1,
    "ytm": 5.24,
    "duration": 6.54,
    "sector": "Sovereign",
    "cusip": "760942BE1",
    "isin": "US760942BE11",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0162",
    "name": "Oman Sultanate of (Government) RegS 6.75% 2048-01-17",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Oman",
    "currency": "USD",
    "issuer": "Oman Sultanate of (Government) RegS",
    "coupon": 6.75,
    "maturity": "2048-01-17",
    "price": 105.29,
    "ytm": 6.3,
    "duration": 11.48,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS1750114396",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0163",
    "name": "Ukraine (Republic of) C Bonds RegS 4.00% 2032-02-01",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Ukraine",
    "currency": "USD",
    "issuer": "Ukraine (Republic of) C Bonds RegS",
    "coupon": 4,
    "maturity": "2032-02-01",
    "price": 83.12,
    "ytm": 10.92,
    "duration": 4.59,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS3261834314",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0164",
    "name": "Brazil Federative Republic of (Govt) 6.63% 2035-03-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Brazil",
    "currency": "USD",
    "issuer": "Brazil Federative Republic of (Govt)",
    "coupon": 6.63,
    "maturity": "2035-03-15",
    "price": 101.57,
    "ytm": 6.38,
    "duration": 6.5,
    "sector": "Sovereign",
    "cusip": "105756CL2",
    "isin": "US105756CL22",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0165",
    "name": "Brazil Federative Republic of (Govt) 7.25% 2056-01-12",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Brazil",
    "currency": "USD",
    "issuer": "Brazil Federative Republic of (Govt)",
    "coupon": 7.25,
    "maturity": "2056-01-12",
    "price": 96.26,
    "ytm": 7.57,
    "duration": 11.78,
    "sector": "Sovereign",
    "cusip": "105756CN8",
    "isin": "US105756CN87",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0166",
    "name": "South Africa (Republic of) 5.75% 2049-09-30",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "South Africa",
    "currency": "USD",
    "issuer": "South Africa (Republic of)",
    "coupon": 5.75,
    "maturity": "2049-09-30",
    "price": 82.75,
    "ytm": 7.31,
    "duration": 11.67,
    "sector": "Sovereign",
    "cusip": "836205BB9",
    "isin": "US836205BB97",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0167",
    "name": "South Africa (Republic of) 5.88% 2030-06-22",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "South Africa",
    "currency": "USD",
    "issuer": "South Africa (Republic of)",
    "coupon": 5.88,
    "maturity": "2030-06-22",
    "price": 102.29,
    "ytm": 3.4,
    "duration": 3.44,
    "sector": "Sovereign",
    "cusip": "836205AY0",
    "isin": "US836205AY00",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0168",
    "name": "Egypt (Arab Republic of) MTN RegS 8.50% 2047-01-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Egypt",
    "currency": "USD",
    "issuer": "Egypt (Arab Republic of) MTN RegS",
    "coupon": 8.5,
    "maturity": "2047-01-31",
    "price": 97.03,
    "ytm": 8.82,
    "duration": 9.45,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS1558078496",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0169",
    "name": "Dominican Republic (Government) RegS 4.88% 2032-09-23",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Dominican Republic",
    "currency": "USD",
    "issuer": "Dominican Republic (Government) RegS",
    "coupon": 4.88,
    "maturity": "2032-09-23",
    "price": 94.83,
    "ytm": 5.89,
    "duration": 5.19,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "USP3579ECH82",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0170",
    "name": "Hungary (Government) RegS 5.50% 2036-03-26",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Europe",
    "country": "Hungary",
    "currency": "USD",
    "issuer": "Hungary (Government) RegS",
    "coupon": 5.5,
    "maturity": "2036-03-26",
    "price": 99.24,
    "ytm": 5.6,
    "duration": 7.39,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS2744128369",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0171",
    "name": "Poland (Republic of) 5.50% 2054-03-18",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Europe",
    "country": "Poland",
    "currency": "USD",
    "issuer": "Poland (Republic of)",
    "coupon": 5.5,
    "maturity": "2054-03-18",
    "price": 90.33,
    "ytm": 6.24,
    "duration": 13.44,
    "sector": "Sovereign",
    "cusip": "731011AZ5",
    "isin": "US731011AZ55",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0172",
    "name": "Poland (Republic of) 5.13% 2034-02-12",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Europe",
    "country": "Poland",
    "currency": "USD",
    "issuer": "Poland (Republic of)",
    "coupon": 5.13,
    "maturity": "2034-02-12",
    "price": 100.27,
    "ytm": 5.34,
    "duration": 6.14,
    "sector": "Sovereign",
    "cusip": "857524AH5",
    "isin": "US857524AH50",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0173",
    "name": "Petronas Capital Ltd MTN RegS 4.55% 2050-04-21",
    "govCorp": "Government-Related",
    "govCorpRaw": "Government-Related (Agency)",
    "region": "Asia-Pacific",
    "country": "Malaysia",
    "currency": "USD",
    "issuer": "Petronas Capital Ltd MTN RegS",
    "coupon": 4.55,
    "maturity": "2050-04-21",
    "price": 83.21,
    "ytm": 5.87,
    "duration": 13.47,
    "sector": "Agency",
    "cusip": null,
    "isin": "USY68856AV83",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0174",
    "name": "Colombia (Republic of) 7.50% 2034-02-02",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Colombia",
    "currency": "USD",
    "issuer": "Colombia (Republic of)",
    "coupon": 7.5,
    "maturity": "2034-02-02",
    "price": 105.75,
    "ytm": 6.51,
    "duration": 5.71,
    "sector": "Sovereign",
    "cusip": "195325EG6",
    "isin": "US195325EG61",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0175",
    "name": "Colombia (Republic of) 6.13% 2041-01-18",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Colombia",
    "currency": "USD",
    "issuer": "Colombia (Republic of)",
    "coupon": 6.13,
    "maturity": "2041-01-18",
    "price": 91.77,
    "ytm": 7.04,
    "duration": 9.21,
    "sector": "Sovereign",
    "cusip": "195325BM6",
    "isin": "US195325BM66",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0176",
    "name": "Panama Republic of (Government) 6.40% 2035-02-14",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Panama",
    "currency": "USD",
    "issuer": "Panama Republic of (Government)",
    "coupon": 6.4,
    "maturity": "2035-02-14",
    "price": 104.3,
    "ytm": 5.75,
    "duration": 6.54,
    "sector": "Sovereign",
    "cusip": "698299BT0",
    "isin": "US698299BT07",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0177",
    "name": "Turkey (Republic of) 9.88% 2028-01-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Turkey",
    "currency": "USD",
    "issuer": "Turkey (Republic of)",
    "coupon": 9.88,
    "maturity": "2028-01-15",
    "price": 105.78,
    "ytm": 5.59,
    "duration": 1.31,
    "sector": "Sovereign",
    "cusip": "900123DF4",
    "isin": "US900123DF45",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0178",
    "name": "Turkey (Republic of) 6.50% 2034-05-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Turkey",
    "currency": "USD",
    "issuer": "Turkey (Republic of)",
    "coupon": 6.5,
    "maturity": "2034-05-15",
    "price": 104.06,
    "ytm": 6.94,
    "duration": 6.02,
    "sector": "Sovereign",
    "cusip": "900123DK3",
    "isin": "US900123DK30",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0179",
    "name": "Mexico (United Mexican States) 6.25% 2037-08-27",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "Mexico",
    "currency": "USD",
    "issuer": "Mexico (United Mexican States)",
    "coupon": 6.25,
    "maturity": "2037-08-27",
    "price": 99.07,
    "ytm": 6.36,
    "duration": 7.87,
    "sector": "Sovereign",
    "cusip": "91087BBT6",
    "isin": "US91087BBT61",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0180",
    "name": "Mexico (United Mexican States) 6.00% 2036-05-07",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "North America",
    "country": "Mexico",
    "currency": "USD",
    "issuer": "Mexico (United Mexican States)",
    "coupon": 6,
    "maturity": "2036-05-07",
    "price": 98.76,
    "ytm": 6.17,
    "duration": 7.31,
    "sector": "Sovereign",
    "cusip": "91087BAZ3",
    "isin": "US91087BAZ31",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0181",
    "name": "Petroleos Mexicanos 7.69% 2050-01-23",
    "govCorp": "Government-Related",
    "govCorpRaw": "Government-Related (Agency)",
    "region": "North America",
    "country": "Mexico",
    "currency": "USD",
    "issuer": "Petroleos Mexicanos",
    "coupon": 7.69,
    "maturity": "2050-01-23",
    "price": 92.25,
    "ytm": 8.45,
    "duration": 10.29,
    "sector": "Agency",
    "cusip": "71654QDD1",
    "isin": "US71654QDD16",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0182",
    "name": "Kenya (Republic of) RegS 9.75% 2031-02-16",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Kenya",
    "currency": "USD",
    "issuer": "Kenya (Republic of) RegS",
    "coupon": 9.75,
    "maturity": "2031-02-16",
    "price": 107.56,
    "ytm": 7.26,
    "duration": 3.65,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS2764839945",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0183",
    "name": "Saudi Arabia (Kingdom of) MTN RegS 4.50% 2046-10-26",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Saudi Arabia",
    "currency": "USD",
    "issuer": "Saudi Arabia (Kingdom of) MTN RegS",
    "coupon": 4.5,
    "maturity": "2046-10-26",
    "price": 79.4,
    "ytm": 6.32,
    "duration": 12.23,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS1508675508",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0184",
    "name": "Saudi Arabia (Kingdom of) MTN RegS 3.63% 2028-03-04",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Saudi Arabia",
    "currency": "USD",
    "issuer": "Saudi Arabia (Kingdom of) MTN RegS",
    "coupon": 3.63,
    "maturity": "2028-03-04",
    "price": 98.54,
    "ytm": 4.61,
    "duration": 1.49,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS1694217495",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0185",
    "name": "Philippines (Republic of) 9.50% 2030-02-02",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Philippines",
    "currency": "USD",
    "issuer": "Philippines (Republic of)",
    "coupon": 9.5,
    "maturity": "2030-02-02",
    "price": 114.63,
    "ytm": 4.87,
    "duration": 2.99,
    "sector": "Sovereign",
    "cusip": "718286AY3",
    "isin": "US718286AY36",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0186",
    "name": "Philippines (Republic of) 6.38% 2034-10-23",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Philippines",
    "currency": "USD",
    "issuer": "Philippines (Republic of)",
    "coupon": 6.38,
    "maturity": "2034-10-23",
    "price": 106.38,
    "ytm": 5.4,
    "duration": 6.42,
    "sector": "Sovereign",
    "cusip": "718286BG1",
    "isin": "US718286BG11",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0187",
    "name": "Indonesia (Republic of) RegS 7.75% 2038-01-17",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Indonesia",
    "currency": "USD",
    "issuer": "Indonesia (Republic of) RegS",
    "coupon": 7.75,
    "maturity": "2038-01-17",
    "price": 115.04,
    "ytm": 5.92,
    "duration": 7.8,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "USY20721AL30",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0188",
    "name": "Indonesia (Republic of) MTN RegS 6.75% 2044-01-15",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Indonesia",
    "currency": "USD",
    "issuer": "Indonesia (Republic of) MTN RegS",
    "coupon": 6.75,
    "maturity": "2044-01-15",
    "price": 105.77,
    "ytm": 6.2,
    "duration": 10.35,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "USY20721BK48",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0189",
    "name": "Nigeria (Federal Republic of) MTN RegS 10.38% 2034-12-09",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Nigeria",
    "currency": "USD",
    "issuer": "Nigeria (Federal Republic of) MTN RegS",
    "coupon": 10.38,
    "maturity": "2034-12-09",
    "price": 119.6,
    "ytm": 7.2,
    "duration": 5.76,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS2948512913",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0190",
    "name": "Nigeria (Federal Republic of) RegS 7.88% 2032-02-16",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Nigeria",
    "currency": "USD",
    "issuer": "Nigeria (Federal Republic of) RegS",
    "coupon": 7.88,
    "maturity": "2032-02-16",
    "price": 105.46,
    "ytm": 6.67,
    "duration": 4.45,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS1566179039",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0191",
    "name": "Angola (Republic of) MTN RegS 9.88% 2037-03-31",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Angola",
    "currency": "USD",
    "issuer": "Angola (Republic of) MTN RegS",
    "coupon": 9.88,
    "maturity": "2037-03-31",
    "price": 105.22,
    "ytm": 9.09,
    "duration": 6.64,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS3328007870",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0192",
    "name": "Chile (Republic of) 3.10% 2041-05-07",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Chile",
    "currency": "USD",
    "issuer": "Chile (Republic of)",
    "coupon": 3.1,
    "maturity": "2041-05-07",
    "price": 74.08,
    "ytm": 5.73,
    "duration": 11.11,
    "sector": "Sovereign",
    "cusip": "168863DS4",
    "isin": "US168863DS48",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0193",
    "name": "Romania (Republic of) MTN RegS 6.63% 2036-05-16",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Romania",
    "currency": "USD",
    "issuer": "Romania (Republic of) MTN RegS",
    "coupon": 6.63,
    "maturity": "2036-05-16",
    "price": 101.55,
    "ytm": 6.41,
    "duration": 7.17,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS3114897633",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0194",
    "name": "Kazakhstan (Republic of) MTN RegS 6.50% 2045-07-21",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Kazakhstan",
    "currency": "USD",
    "issuer": "Kazakhstan (Republic of) MTN RegS",
    "coupon": 6.5,
    "maturity": "2045-07-21",
    "price": 105.44,
    "ytm": 6.01,
    "duration": 11.01,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS1263139856",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0195",
    "name": "Peru (Republic of) 8.75% 2033-11-21",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Peru",
    "currency": "USD",
    "issuer": "Peru (Republic of)",
    "coupon": 8.75,
    "maturity": "2033-11-21",
    "price": 119.83,
    "ytm": 5.41,
    "duration": 5.51,
    "sector": "Sovereign",
    "cusip": "715638AP7",
    "isin": "US715638AP79",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0196",
    "name": "Jamaica (Government) 7.88% 2045-07-28",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Jamaica",
    "currency": "USD",
    "issuer": "Jamaica (Government)",
    "coupon": 7.88,
    "maturity": "2045-07-28",
    "price": 116.93,
    "ytm": 6.33,
    "duration": 10.46,
    "sector": "Sovereign",
    "cusip": "470160CB6",
    "isin": "US470160CB63",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0197",
    "name": "Costa Rica (Republic of) RegS 7.30% 2054-11-13",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Costa Rica",
    "currency": "USD",
    "issuer": "Costa Rica (Republic of) RegS",
    "coupon": 7.3,
    "maturity": "2054-11-13",
    "price": 109.2,
    "ytm": 6.57,
    "duration": 12.6,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "USP3699PGN17",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0198",
    "name": "Morocco (Kingdom of) RegS 6.50% 2033-09-08",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Morocco",
    "currency": "USD",
    "issuer": "Morocco (Kingdom of) RegS",
    "coupon": 6.5,
    "maturity": "2033-09-08",
    "price": 105.25,
    "ytm": 5.59,
    "duration": 5.66,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS2595028700",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0199",
    "name": "Bahrain (Kingdom of) RegS 7.00% 2028-10-12",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Bahrain",
    "currency": "USD",
    "issuer": "Bahrain (Kingdom of) RegS",
    "coupon": 7,
    "maturity": "2028-10-12",
    "price": 99.5,
    "ytm": 7.25,
    "duration": 1.98,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS1405766541",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0200",
    "name": "Serbia (Republic of) MTN RegS 6.00% 2034-06-12",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Serbia",
    "currency": "USD",
    "issuer": "Serbia (Republic of) MTN RegS",
    "coupon": 6,
    "maturity": "2034-06-12",
    "price": 100.63,
    "ytm": 5.9,
    "duration": 6.15,
    "sector": "Sovereign",
    "cusip": null,
    "isin": "XS2838999691",
    "sourceEtf": "EMB"
  },
  {
    "id": "BND-0201",
    "name": "Panama Republic of (Government) 3.87% 2060-07-23",
    "govCorp": "Government",
    "govCorpRaw": "Government",
    "region": "Emerging Markets",
    "country": "Panama",
    "currency": "USD",
    "issuer": "Panama Republic of (Government)",
    "coupon": 3.87,
    "maturity": "2060-07-23",
    "price": 65.3,
    "ytm": 6.41,
    "duration": 15.11,
    "sector": "Sovereign",
    "cusip": "698299BL7",
    "isin": "US698299BL70",
    "sourceEtf": "EMB"
  }
];

export const REGIONS = [...new Set(BONDS.map(b => b.region))].sort();
export const SECTORS = [...new Set(BONDS.map(b => b.sector))].sort();
export const GOV_CORP_TYPES = [...new Set(BONDS.map(b => b.govCorp))].sort();
export const YTM_MIN = Math.floor(Math.min(...BONDS.map(b => b.ytm)) * 10) / 10;
export const YTM_MAX = Math.ceil(Math.max(...BONDS.map(b => b.ytm)) * 10) / 10;
export const DURATION_MIN = Math.floor(Math.min(...BONDS.map(b => b.duration)) * 2) / 2;
export const DURATION_MAX = Math.ceil(Math.max(...BONDS.map(b => b.duration)) * 2) / 2;
